<?php
declare(strict_types=1);

// Stytch SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

StytchUtility::setRegistrar(function (StytchUtility $u): void {
    $u->clean = [StytchClean::class, 'call'];
    $u->done = [StytchDone::class, 'call'];
    $u->make_error = [StytchMakeError::class, 'call'];
    $u->feature_add = [StytchFeatureAdd::class, 'call'];
    $u->feature_hook = [StytchFeatureHook::class, 'call'];
    $u->feature_init = [StytchFeatureInit::class, 'call'];
    $u->fetcher = [StytchFetcher::class, 'call'];
    $u->make_fetch_def = [StytchMakeFetchDef::class, 'call'];
    $u->make_context = [StytchMakeContext::class, 'call'];
    $u->make_options = [StytchMakeOptions::class, 'call'];
    $u->make_request = [StytchMakeRequest::class, 'call'];
    $u->make_response = [StytchMakeResponse::class, 'call'];
    $u->make_result = [StytchMakeResult::class, 'call'];
    $u->make_point = [StytchMakePoint::class, 'call'];
    $u->make_spec = [StytchMakeSpec::class, 'call'];
    $u->make_url = [StytchMakeUrl::class, 'call'];
    $u->param = [StytchParam::class, 'call'];
    $u->prepare_auth = [StytchPrepareAuth::class, 'call'];
    $u->prepare_body = [StytchPrepareBody::class, 'call'];
    $u->prepare_headers = [StytchPrepareHeaders::class, 'call'];
    $u->prepare_method = [StytchPrepareMethod::class, 'call'];
    $u->prepare_params = [StytchPrepareParams::class, 'call'];
    $u->prepare_path = [StytchPreparePath::class, 'call'];
    $u->prepare_query = [StytchPrepareQuery::class, 'call'];
    $u->graphql_body = [StytchGraphql::class, 'body'];
    $u->graphql_errors = [StytchGraphql::class, 'errors'];
    $u->result_basic = [StytchResultBasic::class, 'call'];
    $u->result_body = [StytchResultBody::class, 'call'];
    $u->result_headers = [StytchResultHeaders::class, 'call'];
    $u->transform_request = [StytchTransformRequest::class, 'call'];
    $u->transform_response = [StytchTransformResponse::class, 'call'];
});
